App\Entity\Cms\PostCategory:
  security: is_granted("ROLE_USER")
  collectionOperations:
    get:
      normalization_context:
        groups: ['list:cms:category']
      filters: ['timeAt.order_filter','timeAt.date_filter','category.search_filter']
  itemOperations:
    get:
      normalization_context:
        groups: ['read:cms:category']