security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Core\User
        property: 'email'

  role_hierarchy:
    ROLE_ADMIN: ROLE_ADMIN_WORKER
    ROLE_ADMIN_WORKER: ROLE_BUSINESS
    ROLE_BUSINESS: ROLE_BUSINESS_WORKER
    ROLE_BUSINESS_WORKER: ROLE_BUSINESS_ADMINISTRATION
    ROLE_BUSINESS_ADMINISTRATION: ROLE_USER

  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
      provider: app_user_provider
    api:
      pattern: ^/api/
      stateless: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker
      jwt: ~
    main:
      entry_point: App\Security\AdminAuthenticator
      form_login:
        # "app_login" is the name of the route created previously
        login_path: app_login
        check_path: app_login
        success_handler: App\Security\FormAuthenticator
      json_login:
        check_path: /authentication_token
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      custom_authenticator: App\Security\AdminAuthenticator
      user_checker: App\Security\UserChecker
      provider: app_user_provider
      logout:
        path: logout

  access_control:
    - { path: ^/docs, roles: PUBLIC_ACCESS }
    - { path: ^/api/docs.json, roles: PUBLIC_ACCESS }
    - { path: ^/api/reset_passwords, roles: PUBLIC_ACCESS, method: "POST" }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/heyBoss, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/reset, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_BUSINESS_ADMINISTRATION }
    - { path: ^/authentication_token, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
