# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        media_file:
            uri_prefix:         '%app.path.media_file%'
            upload_destination: '%kernel.project_dir%/public%app.path.media_file%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        media_object:
            uri_prefix:         '%app.path.mediaobject_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.mediaobject_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer