App\Entity\Calendar\CalendarUser:
  collectionOperations:
    get:
      filters: ['timeAt.order_filter','timeAt.date_filter']
      normalization_context:
        groups: ['list:calendar:user']
  itemOperations:
    get:
      normalization_context:
        groups: ['read:calendar:user']