App\Entity\Client\ResetPassword:
  attributes:
    normalization_context:
      groups: ['read:reset']
    denormalization_context:
      groups: ['write:reset']
  collectionOperations:
    post: ~
    get: ~
  itemOperations:
    get: ~
