controllers:
  resource: ../src/Controller/
  type: attribute
dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
authentication_token:
  path: /authentication_token
  methods: ['POST']
