App\Entity\Commerce\Product:
  security: is_granted("ROLE_USER")
  collectionOperations:
    get:
      normalization_context:
        groups: ['list:product']
      filters: ['listProduct.search_filter','name.search_filter']
  itemOperations:
    get:
      normalization_context:
        groups: ['read:product']